### ISSUE TITLE
Will LLMFarm support llama2?

### ISSUE THREAD

**Issue by realcarlos** [guinmoon/LLMFarm#4]

**Comment by guinmoon** [comment]
if someone makes a ggml version

**Comment by jhen0409** [comment]
FYI: q2_k is not working in my tests, I got `bad_alloc` crash or `unexpectedly reached end of file` by enabling `Extended Virtual Addressing`. q4_0 works fine.

I also trying integrate llama.cpp to my iOS apps ([latest commit](https://github.com/ggerganov/llama.cpp/commit/2f9cf974a066ac0e03fbb235d834b01b0164d743)), the problem is looks same with here.

**Comment by guinmoon** [comment]
> FYI: q2_k is not working in my tests, I got `bad_alloc` crash or `unexpectedly reached end of file` (enabling `Extended Virtual Addressing`). q4_0 works fine.
> 
> I also trying integrate llama.cpp to my iOS apps ([latest commit](https://github.com/ggerganov/llama.cpp/commit/2f9cf974a066ac0e03fbb235d834b01b0164d743)), the problem is looks same with here.

In the current version of llmfarm, I use [this commit](https://github.com/ggerganov/llama.cpp/commit/6e7cca404748dd4b1a3affd0d1296e37f4ac0a6f). q2_k works fine on iphone(without metal) and Mac.

**Comment by guinmoon** [comment]
> FYI: q2_k is not working in my tests, I got `bad_alloc` crash or `unexpectedly reached end of file` (enabling `Extended Virtual Addressing`). q4_0 works fine.
> 
> I also trying integrate llama.cpp to my iOS apps ([latest commit](https://github.com/ggerganov/llama.cpp/commit/2f9cf974a066ac0e03fbb235d834b01b0164d743)), the problem is looks same with here.

You may have compiled llmfarm_core with -DGGML_QKK_64 in Package.swift. You need to either rebuild the project without this flag, or requantize the models for QKK_64.
