### ISSUE TITLE
Add support for Llama 3

### ISSUE THREAD

**Issue by lajlev** [guinmoon/LLMFarm#57]
Could be cool if it could run on iOS

**Comment by yayoimizuha** [comment]
![IMG_0044](https://github.com/guinmoon/LLMFarm/assets/32425706/16d4ce6e-61d0-4928-a00f-9115c7550f49)
I’m using Llama-3 model at TestFlight app, Something is wrong?

**Comment by lajlev** [comment]
How do I add it?

From: Tomokazu Katayama ***@***.***>
Date: Tuesday, 23 April 2024 at 08.04
To: guinmoon/LLMFarm ***@***.***>
Cc: Michael Lajlev ***@***.***>, Author ***@***.***>
Subject: Re: [guinmoon/LLMFarm] Add support for Llama 3 (Issue #57)

IMG_0044.png (view on web)<https://github.com/guinmoon/LLMFarm/assets/32425706/16d4ce6e-61d0-4928-a00f-9115c7550f49>
I’m using Llama-3 model at TestFlight app, Something is wrong?

**Comment by yayoimizuha** [comment]
![IMG_0046](https://github.com/guinmoon/LLMFarm/assets/32425706/fee1a5c7-84c3-4067-a824-f5c3312a2e7c)

I used below prompt.
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. <|eot_id|><|start_header_id|>user<|end_header_id|>
{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

And,I used this quantized model.
https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct.Q5_K_M.gguf

Notes: I’m using iPad Pro 11inch Gen 4(2022), sorry for poorly English because not English speaker.

**Comment by yayoimizuha** [comment]
Config:
![IMG_0047](https://github.com/guinmoon/LLMFarm/assets/32425706/eec66532-1565-4467-8f27-5dc3e30153ee)

Used prompt:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. <|eot_id|><|start_header_id|>user<|end_header_id|>
{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

Model file from: https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct.Q5_K_M.gguf

Using: iPad Pro ‘11 Gen 4(2022) (512GB model)

Sorry for poorly English because I’m Japanese.

**Comment by yayoimizuha** [comment]
P.S. Used App ver.:
![IMG_0048](https://github.com/guinmoon/LLMFarm/assets/32425706/51cae319-ab86-4306-ac83-f6c0afcb7e22)

**Comment by amostamu** [comment]
maybe llama 3 is not good at Japanese , test llama 3 70b with your prompt.  Output is English with a lot of !!!!!

**Comment by lajlev** [comment]
Thanks for your responses. I'll try it out 🚀
